### ISSUE TITLE
Грешна општина во графот „Географска дистрибуција на незгодите по општини“ 

### ISSUE THREAD

**Issue by ghost** [novica/natochak#9]
![Image](https://i.imgur.com/0h0mI5R.png)

**Comment by novica** [comment]
па, всушност не е грешна општина. туку само label-от за општината ѓ. петров е ставен малку понадесно веројатно поради тоа што немало место до - околу карпош на начинот на кој што се генерира мапата. според мапата карпош и ѓ. петров имаат ист број на незгоди па фактички личи како тоа да е еден регион. што можеби е супер за носталгичните ѓ. петровчани кои се уште им пишува на лк. дека се од карпош. ;-)

Забуната дополнително ја создава тоа што ја нема лабелата за аеродром.
